Update dependencies to latest releases
ClusterLabs/ha_cluster_exporter pull request #192
Opened 2021-05-03 11:47 UTC by dirkmueller

Also require go 1.14, which is the oldest still maintained
golang version (and some of the dependencies require at
least 1.14)

2021-05-03 11:57 UTC, stefanotorresi approved these changes
Thank you!

2021-05-03 11:58 UTC, stefanotorresi requested changes
Actually, could you please update https://github.com/ClusterLabs/ha_cluster_exporter/blob/master/packaging/obs/prometheus-ha_cluster_exporter/prometheus-ha_cluster_exporter.spec accordingly?

2021-05-03 12:28 UTC, dirkmueller commented
@stefanotorresi done

2021-05-04 08:36 UTC, stefanotorresi approved these changes

2021-05-04 08:36 UTC, merged